FROM alpine:3.18.4
RUN apk add --no-cache \
        npm \
        openssl-dev && \
    adduser \
        -D \
        -g '' \
        app && \
	npm install \
		-g \
		@foundryvtt/foundryvtt-cli;
USER app
ENTRYPOINT ["fvtt"]
